---
- name: Tomcat deployment playbook
  hosts: tomcat-nodes
  #become: yes
  #become_method: sudo
  #remote_user: root
  tasks:

  - name: Add ansible group
    group:
      name: ansible

  - name: Add ansible user
    user:
      name: tomcat
      group: ansible
      system: yes
      
  roles:
    - install_tomcat
    - clone_ansible_deploy
    - create_cronjob
