---
- name: Create a deploy directory
  file:
    path: /opt/deployweb
    state: directory
    owner: ansible
    group: ansible

- name: Clone ansible deploy
  git:
    repo: https://github.com/DanJake/ansible_for_web.git
    dest: "{{ web_deploy }}"
  become: yes
  become_user: ansible

- name: Download some content
  gc_storage:
    bucket: sgdzsgfsdg
    object: deploy.sh
    dest: /opt/deployweb/deploy.sh

- name: Change file ownership, group and permissions
  file:
    path: /opt/deployweb/deploy.sh
    owner: ansible
    group: ansible
    mode: '0644'
