---
- cron:
    name: "check web app update"
    minute: "*/1"
    user: ansible
    job: "source {{ web_deploy }}/set_prod_var.sh $$ /usr/bin/ansible-playbook {{ web_deploy }}/deploy.yml"

- cron:
    name: "check deploy file update"
    minute: "*/1"
    user: ansible
    job: "/bin/sh -c 'cd {{ web_deploy }} && /usr/bin/git pull -q origin main'"

- name: restart cron
  service:
    name: cron
    state: restarted
